// <auto-generated />
using System;
using ApiDanielLucas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDanielLucas.Migrations
{
    [DbContext(typeof(ApiDanielLucasContext))]
    partial class ApiDanielLucasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiDanielLucas.Models.aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("escola_id")
                        .HasColumnType("int");

                    b.Property<string>("mae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matricula")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("professor_id")
                        .HasColumnType("int");

                    b.Property<string>("rma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("ApiDanielLucas.Models.escola", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("aluno_id")
                        .HasColumnType("int");

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("professor_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("escola");
                });

            modelBuilder.Entity("ApiDanielLucas.Models.professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("componente_curricular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("escola_id")
                        .HasColumnType("int");

                    b.Property<string>("mae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("matricula")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("professor");
                });
#pragma warning restore 612, 618
        }
    }
}
